version: '3.3'

services:
    api-server:
        build: ./api-server
        restart: always
        ports:
            - 443:443
        volumes:
            - ./api-server:/usr/src/app
        links:
            - redis
        environment: 
            - REDIS_URL=redis://cache
            - REDIS_PASSWORD=Banana
            - PGUSER=cryapi
            - PGDATABASE=crydb
            - PGPASSWORD=apple
    postgres:
        build: ./postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: "apple"
            POSTGRES_DB: "crydb"
        ports:
            - 5432:5432
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    redis:
        build: ./redis/

        environment:
            - REDIS_PASSWORD=Banana
        command: redis-server --requirepass Banana
        container_name: cache
        expose:
            - 6379

        