version: '3.3'

services:
    api-server:
        build: ./api-server
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./api-server:/usr/src/app
        links:
            - redis
        environment: 
            - REDIS_URL=redis://cache
            - REDIS_PASSWORD=Banana
            - PGUSER=${PGUSER}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGADDRESS=${PGADDRESS}
    redis:
        build: ./redis/

        environment:
            - REDIS_PASSWORD=Banana
        command: redis-server --requirepass Banana
        container_name: cache
        expose:
            - 6379

        
