version: '3.3'
services:
  api-server:
    command: npm test
    environment: 
      - PGADDRESS=postgres
  postgres:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432